---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: include credentials
      include_vars: credentials.yml

    - name: Collect the list of the existing VM
      vmware.vmware_rest.vcenter_vm_info:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: false
      register: existing_vms
      until: existing_vms is not failed

    - name: debug
      debug:
        var: existing_vms

